# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-06 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('alias', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterCan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveSmallIntegerField()),
                ('balance', models.SmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('deliverd_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_cans_delivered', to=settings.AUTH_USER_MODEL)),
                ('delivered_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_cans', to='delivery.Customer')),
            ],
        ),
    ]
